Repository Am10aN16/webD_projects_beginners_Hacktoberfest22, pull requests merged in 2022-10, with the labels that each got.

#1 Trees Added
  TREE/takeInputAndPrintRecursive.cpp
  TREE/takeInputAndPrintRecursive.exe
Labels: question, hacktoberfest-accepted

#2 Linked List Added
  LInked_List/Linked_list.cpp
  LInked_List/Linked_list.exe
  LInked_List/delete_node.cpp
  LInked_List/delete_node.exe
  LInked_List/insert_node_in_ll.cpp
  LInked_List/insert_node_in_ll.exe
  LInked_List/mid_point.cpp
  LInked_List/mid_point.exe
  LInked_List/take_input.cpp
  LInked_List/take_input.exe
Labels: good first issue, hacktoberfest-accepted

#4 stack Added
  stack/dynamic_array.cpp
  stack/dynamic_array.exe
  stack/stack_using_LL.cpp
  stack/stack_using_LL.exe
  stack/stack_using_array.cpp
  stack/stack_using_array.exe
  stack/template.cpp
Labels: hacktoberfest-accepted

#5 tim sort.cpp
  tim sort.cpp
Labels: hacktoberfest-accepted

#6 Create subset.cpp
  Recursion/nqueen.cpp
  comsum1.cpp
  subset.cpp
Labels: enhancement, hacktoberfest-accepted

#7 Added painter partision problem code using C++
  painterparticition.cpp
Labels: good first issue, hacktoberfest-accepted

#8 Added Book Allocation problem sol using C++
  bookallocate.cpp
Labels: enhancement, good first issue, hacktoberfest-accepted

#9 Added Valid palindrome problem of leetcode
  validPalindromeleetcode.cpp
Labels: enhancement, good first issue, hacktoberfest-accepted

#12 stiver-sde
  stiver-sde/Best Time to Buy and Sell Stock.cpp
  stiver-sde/Find the DuplicateNumber.cpp
  stiver-sde/Majority Element.cpp
  stiver-sde/Maximum Subarray.cpp
  stiver-sde/MergeIntervals.cpp
  stiver-sde/NextPermutation.cpp
  stiver-sde/Pascal's Triangle.cpp
  stiver-sde/Pow(x, n).cpp
  stiver-sde/Reverse Pairs.cpp
  stiver-sde/RotateImage.cpp
  stiver-sde/Search a 2D Matrix.cpp
  stiver-sde/Set Matrix Zeroes.cpp
  stiver-sde/Sort Colors.cpp
  stiver-sde/Unique Paths.cpp
Labels: enhancement, good first issue, hacktoberfest-accepted

#16 changes done
  stiver-sde/knapsack.cpp
Labels: enhancement, good first issue, hacktoberfest-accepted

#17 code written
  DijkstrasAlgo.cpp
Labels: good first issue, hacktoberfest-accepted

#19 Create DutchNationalFlagAlgo.cpp
  DutchNationalFlagAlgo.cpp
Labels: enhancement, hacktoberfest-accepted

#20 Create reverseArrayUsingrecursion.cpp
  reverseArrayUsingrecursion.cpp
Labels: good first issue, hacktoberfest-accepted

#23 Create number_of_ways.py
  number_of_ways.py
Labels: enhancement, good first issue, hacktoberfest-accepted

#26 changes on graph traversal
  graphtraversal.cpp
Labels: enhancement, good first issue, hacktoberfest-accepted

#28 created cpp solution of 100-same-tree
  LInked_List/160-intersection-of-two-linked-lists.cpp
  TREE/100-same-tree.cpp
Labels: enhancement, good first issue, hacktoberfest-accepted

#29 changes made
  length.cpp
Labels: enhancement, hacktoberfest-accepted

#30 Create adj_list.cpp
  adj_list.cpp
Labels: enhancement, good first issue, hacktoberfest-accepted

#31 Added file
  Array/Product_Of_Array_Except_Self.cpp
Labels: good first issue, hacktoberfest-accepted

#36 split linked list in parts
  LInked_List/split linked list in parts
Labels: enhancement, good first issue, hacktoberfest-accepted

#35 Bellman-ford Algorithm
  Bellman-ford Algorithm
Labels: enhancement, good first issue, hacktoberfest-accepted

#37 Create uploadJsonToS3.js
  uploadJsonToS3.js
Labels: enhancement, hacktoberfest-accepted

#34 Kadane's Algorithm
  kadane's Algorithm
Labels: good first issue, hacktoberfest-accepted

#38 automation of motion detect python code
  python/motion_detect.py
Labels: hacktoberfest-accepted

#43 added code of knapsack problem
  knapsack-problem.cpp
Labels: hacktoberfest-accepted
